# Generated by Django 3.1.7 on 2021-07-07 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonprofile',
            name='salon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.salon'),
        ),
    ]
