# Generated by Django 3.1.7 on 2021-07-14 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_buyer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='email',
            new_name='buyer_email',
        ),
        migrations.RenameField(
            model_name='buyer',
            old_name='name',
            new_name='buyer_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.buyer'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.buyer'),
        ),
    ]
